{{- if and .Values.api.enabled .Values.api.metrics.vmPodScrape.enabled -}}
apiVersion: operator.victoriametrics.com/v1beta1
kind: VMPodScrape
metadata:
  name: terrakube-api
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
    {{- with .Values.api.metrics.vmPodScrape.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "terrakube.metricsSelectorLabels" (dict "svc" "api" "root" $) | nindent 6 }}
  podMetricsEndpoints:
    - port: {{ .Values.api.metrics.port | default "http" }}
      path: {{ .Values.api.metrics.path | default "/actuator/prometheus" }}
      interval: {{ .Values.api.metrics.interval | default "30s" }}
      honorLabels: true
{{- end -}}
