{{- if .Values.registry.otel.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: terrakube-registry-otel-config
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
data:
  {{- include "terrakube.otelEnv" (dict "svc" "registry" "root" $) | nindent 2 }}
{{- end -}}
