{{- if .Values.executor.otel.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: terrakube-executor-otel-config
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
data:
  {{- include "terrakube.otelEnv" (dict "svc" "executor" "root" $) | nindent 2 }}
{{- end -}}
