{{- if .Values.api.otel.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: terrakube-api-otel-config
  labels:
    {{- include "terrakube.labels" . | nindent 4 }}
data:
  {{- include "terrakube.otelEnv" (dict "svc" "api" "root" $) | nindent 2 }}
{{- end -}}
