global:
  observability:
    environment: staging
api:
  otel:
    enabled: true
    otlp:
      endpoint: http://otel-collector.observability:4318
  metrics:
    vmPodScrape:
      enabled: true
executor:
  otel:
    enabled: true
    otlp:
      endpoint: http://otel-collector.observability:4318
  metrics:
    vmPodScrape:
      enabled: true
registry:
  otel:
    enabled: true
    otlp:
      endpoint: http://otel-collector.observability:4318
  metrics:
    vmPodScrape:
      enabled: true
