apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-otel-kube-stack
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://open-telemetry.github.io/opentelemetry-helm-charts
      chart: opentelemetry-kube-stack
      targetRevision: "0.20.5"
      helm:
        valueFiles:
          - $values/examples/observability/values/otel-kube-stack.values.yaml
    - repoURL: https://github.com/terrakube-io/terrakube-helm-chart
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
