apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: obs-victoria-logs
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  sources:
    - repoURL: https://victoriametrics.github.io/helm-charts
      chart: victoria-logs-single
      targetRevision: "0.13.9"
      helm:
        valueFiles:
          - $values/examples/observability/values/victoria-logs-single.values.yaml
    - repoURL: https://github.com/terrakube-io/terrakube-helm-chart
      targetRevision: main
      ref: values
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
